name: CD

on:
  push:
    tags:
      - v*
    branches:
      - 'main'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          target: ${{ matrix.target }}
          args: --release -o dist --find-interpreter
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-wheels-${{ matrix.target }}
          path: dist
          retention-days: 3
          compression-level: 0

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          key: x64
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          target: x64
          args: --release -o dist --find-interpreter
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-wheels-x64
          path: dist
          retention-days: 3
          compression-level: 0

  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          key: x86_64
      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          target: x86_64
          manylinux: manylinux_2_28
          before-script-linux: |
            yum install -y openssl-devel
            export OPENSSL_NO_VENDOR=1
          args: --release -o dist --find-interpreter
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheels-x86_64
          path: dist
          retention-days: 3
          compression-level: 0

  linux-aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          key: aarch64
      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          target: aarch64
          manylinux: manylinux_2_28
          before-script-linux: |
            yum install -y openssl-devel
            export OPENSSL_NO_VENDOR=1
          args: --release -o dist --find-interpreter
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheels-aarch64
          path: dist
          retention-days: 3
          compression-level: 0

  # TODO Add pypy

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ macos, linux-x86_64, linux-aarch64, windows ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: '*-wheels-*'
          path: artifacts
      - name: Collect wheels
        run: |
          mkdir -p dist
          find artifacts -name '*.whl' -exec mv {} dist/ \;
          ls -la dist/
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_UPLOAD_TOKEN }}
        run: |
          pip install --upgrade twine
          twine check dist/*
          twine upload --skip-existing --verbose dist/*
